### PR TITLE
Update root users run.properties

### PR DESCRIPTION
**Pull request by moonraker595**
Expanding the list of root users so others can log in and see data for testing purposes.

### CODE REVIEW

**Review by patrick-austin — COMMENTED** [review]
As the images from this repo are also used by the DOI tests, merging this would cause test failures (checked this locally by modifying my local run.properties). There are tests to ensure that "normal" users can only see what they should be allowed to, but the account we use is `Hunter203` who would now have permissions to see everything. 

I've experimented with build args and environment variables, but I can't find an elegant solution for this. Ideally I think using environment variables would be good, I tried `sed`ing `run.properties` using https://docs.payara.fish/community/docs/documentation/ecosystem/docker-images/server-image-overview.html#executing-custom-scripts-before-domain-startup but at this point in time `run.properties` doesn't exist - I guess the zip we generate isn't unzipped until the boot commands run?

I had more luck with the build args.
```Dockerfile
ARG ROOT_USER_NAMES="simple\/root"
RUN sed -i -e "s/^rootUserNames = simple\/root/rootUserNames = $ROOT_USER_NAMES/" $DEPLOY_DIR/unpacked/WEB-INF/classes/run.properties
```

And then in the `docker-compose.yaml`
```yaml
    args:
      ROOT_USER_NAMES: simple/root simple/doiminter simple/Hunter203 simple/hunter203
```

Gave me the changed file inside the container. Downside is you've got to rebuild if you want to change it, when in principle I don't think you should have to.

I don't do much Docker stuff so not sure what else to try. It might be possible to get the env working but maybe it's more trouble than it's worth and using build args is good enough?

**Comment by moonraker595** [comment]
Thanks for looking into that, it's been a while since I've been around the DOI code and hadn't considered that, so good spot. I think the build args solution is fine and I can't think of a better, permanent option. 

I don't think we can get away from the fact that we need 2 separate images though. 
(Just for transparency; I don't build the icat image in my docker-compose locally for the upload service, I take the whole icat stack from harbor (icat server, auth, test data) for speed).

Here are some more options, I could;
- create a new branch, make the changes to root users and push it, this would allow the CI to create a new image in harbor for me to use with the added root users.
- make your suggested changes, then add another build option in the workflow to build two images, one with the added root users and one without.
- make the changes to root users locally, and build and push an image manually.

At the moment, this repo builds and pushes a harbor image that works with the doi service, I don't want to complicate that. If I create a new branch it may be lingering around for years. Given that I only need the extra root users for local testing rather than any automated testing, I'm inclined to build and push the image to harbor manually.

I'll report back, Thanks for you effort 👍

**Comment by moonraker595** [comment]
I've built a new image with the root users which seems to do the job:
`docker pull harbor.stfc.ac.uk/icat/icat_5:root_users`
I think we can close this PR now.

**Comment by patrick-austin** [comment]
> I don't think we can get away from the fact that we need 2 separate images though. (Just for transparency; I don't build the icat image in my docker-compose locally for the upload service, I take the whole icat stack from harbor (icat server, auth, test data) for speed).

Yeah I also would normally use the images as is, except for workarounds like this. Yesterday I don't think I really thought about the fact that we'd be replacing the `image` key with `build` in order to use the build args in a docker-compose.yaml, which then requires `context` to be specified. I don't know if it's possible to somehow specify the context as the harbor image and then "rebuild" it with the args, looking at https://docs.docker.com/compose/compose-file/build/#using-build-and-image it seemed to be an either/or situation.

I think you're right in that pushing a second image is probably the most pragmatic solution. Another approach could be to pass environment variables to the `testdata` container that, rather than using `rootUserNames`, creates additional ICAT rules that give certain uses "read all" access, i.e. put them  in a Grouping which has a R Rule for every table. We'd have more control than trying to modify with Payara shell scripts, but would need to change the Python scripting in `testdata` to account for it. So too much work for what we need here compared to the two image approach.

**Comment by moonraker595** [comment]
> Another approach could be to pass environment variables to the `testdata` container that, rather than using `rootUserNames`, creates additional ICAT rules that give certain uses "read all" access, i.e. put them in a Grouping which has a R Rule for every table

Agreed. I guess the reason we can't use this for the doi service is because I'm reusing usernames. In the long run, we should add a bunch of new users, with different access levels to the test data.... the but "lazy man's" approach works fine for now! thanks, I'll go ahead and close this PR.

**Pull request closed without merging**
